### ISSUE TITLE
libsubstrate.dylib for arm64

### ISSUE THREAD

**Issue by lemonhead94** [BishopFox/theos-jailed#3]
Hey Guys when I try to compile a tweak for arm64 Architecture, I get the following error message.
Could it be, that you guys forgot to upload the right libsubstrate.dylib?

Makefile: ARCHS = arm64

[...]libsubstrate.dylib, file was built for armv7 which is not the architecture being linked (arm64):[...]

**Comment by 0xhaggis** [comment]
Hi, no we didn't forget - we don't support 64bit right now. As a workaround you can use lipo to extract the armv7 binary from an app, thereby removing the 64bit version of the app. Theos-jailed will work with that. If you really, truly need 64bit I'm afraid you're out of luck for now.

**Comment by hubert3** [comment]
Will a lipo'd 32-bit only binary run on a iPhone 5s?

**Comment by 0xhaggis** [comment]
Yes, I'm currently doing it on an iPhone 6.

**Comment by shuoshi** [comment]
a quick fix is to use install_name_tool

here's what I did

1. download cydiasubstrate 0.9.6 from [here](http://ipod-touch-max.ru/cydia/index.php?cat=package&id=32802#.VwckdRN97OY)

2. extract CydiaSubstrate 

> dpkg -x  cydiasubstrate.deb

then copy Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate to theos-jailed/lib and rename it as cydiasubstrate.dylib, then execute

> install_name_tool -id @executable_path/CydiaSubstrate ./libsubstrate.dylib

copy Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate to PatchApp dir and execute

> install_name_tool -id CydiaSubstrate ./CydiaSubstrate

3. check everything is right with otool

>otool -L PatchApp/CydiaSubstrate 

it should output
>libsubstrate.dylib (architecture armv6):
	CydiaSubstrate (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 7.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 100.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1198.0.0)
libsubstrate.dylib (architecture armv7):
	CydiaSubstrate (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 7.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 100.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1198.0.0)
libsubstrate.dylib (architecture arm64):
	CydiaSubstrate (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 100.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1198.0.0)

in Makefile add 
>ARCHS = armv7 armv7s arm64
on the first line

and run make again.

check your dylib in obj dir

> otool -L obj/test.dylib

u should got

>obj/test.dylib (architecture armv7):
	/usr/lib/test.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1280.25.0)
	/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1280.38.0)
	@executable_path/CydiaSubstrate (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore (compatibility version 1.0.0, current version 601.1.46)
	/System/Library/Frameworks/Security.framework/Security (compatibility version 1.0.0, current version 0.0.0)
	/System/Library/Frameworks/UIKit.framework/UIKit (compatibility version 1.0.0, current version 3512.60.7)
	/System/Library/Frameworks/CFNetwork.framework/CFNetwork (compatibility version 1.0.0, current version 758.3.15)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 8.0.0)
obj/test.dylib (architecture armv7s):
	/usr/lib/test.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1280.25.0)
	/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1280.38.0)
	@executable_path/CydiaSubstrate (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore (compatibility version 1.0.0, current version 601.1.46)
	/System/Library/Frameworks/Security.framework/Security (compatibility version 1.0.0, current version 0.0.0)
	/System/Library/Frameworks/UIKit.framework/UIKit (compatibility version 1.0.0, current version 3512.60.7)
	/System/Library/Frameworks/CFNetwork.framework/CFNetwork (compatibility version 1.0.0, current version 758.3.15)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 8.0.0)
obj/test.dylib (architecture arm64):
	/usr/lib/test.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1280.25.0)
	/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1280.38.0)
	@executable_path/CydiaSubstrate (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore (compatibility version 1.0.0, current version 601.1.46)
	/System/Library/Frameworks/Security.framework/Security (compatibility version 1.0.0, current version 0.0.0)
	/System/Library/Frameworks/UIKit.framework/UIKit (compatibility version 1.0.0, current version 3512.60.7)
	/System/Library/Frameworks/CFNetwork.framework/CFNetwork (compatibility version 1.0.0, current version 758.3.15)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

patch again, and put it to my iPhone6

> Apr  8 11:19:40 buaacss xin[2048] <Warning>: [BF] Constructor entry

wish u have good luck~~

**Comment by Dry05** [comment]
What's the difference? Does this give us the possibility to use arm64 dylibs in the ipa? Cuz that would be awesome!!

**Comment by shuoshi** [comment]
extactly，its arm64 dylib together with armv7 and armv7s，could be used to patch the most recent package of any app like wechat and etc.

**Comment by Dry05** [comment]
Could you please explain how to do it again? I did what you said but I think it's not how it's supposed to work could explain a bit less complicated or send me an email?

**Comment by shuoshi** [comment]
I steal this project and create a new project https://github.com/shuoshi/theos-jailed, I'd like to create a pull request once I could compile 64bit iSpy and cycript.

**Comment by Dry05** [comment]
hi I used your way now my output after the dylib is this: Making all for tweak BDaySpotify2...
 Linking tweak BDaySpotify2...
ld: warning: invalid -install_name (@executable_path/CydiaSubstrate) in dependent dylib (/Users/Scrouble/spotifypatch/theos/lib/libsubstrate.dylib). Dylibs/frameworks which might go in dyld shared cache cannot link with dylib that uses @rpath, @loader_path, etc.
ld: warning: invalid -install_name (@executable_path/CydiaSubstrate) in dependent dylib (/Users/Scrouble/spotifypatch/theos/lib/libsubstrate.dylib). Dylibs/frameworks which might go in dyld shared cache cannot link with dylib that uses @rpath, @loader_path, etc.
ld: warning: invalid -install_name (@executable_path/CydiaSubstrate) in dependent dylib (/Users/Scrouble/spotifypatch/theos/lib/libsubstrate.dylib). Dylibs/frameworks which might go in dyld shared cache cannot link with dylib that uses @rpath, @loader_path, etc. when injecting this dylib into the ipa it still crashes pls help one more time

**Comment by shuoshi** [comment]
Take a look at your crash log in system privacy and in Xcode device console

**Comment by Dry05** [comment]
i already did i think this does the same thing when using lipo separately so arm64 code in the dylibs we compile is still not supported i hope the original developers of these-jailed update it soon for 64bit devices

**Comment by shuoshi** [comment]
Are u sure your ipa is arm64 arch? I only got crash when it armv7 only

**Comment by Dry05** [comment]
yeah but wait in your modified theos-jailed you included lipo -thin armv7 so it's automatically armv7 Ripa only or is there another option?

**Comment by shuoshi** [comment]
Sorry for comment that line... My fault, Or2

**Comment by Dry05** [comment]
So I need to remove the -thin line from the patchapp.sh file?

**Comment by shuoshi** [comment]
Right, besides I forgot to replace the CydiaSubstrate in PatchApp dir. The bug is fixed now, and I've tested it on the latest build of Some apps in store. No crash now! Sorry for my mistake

**Comment by Dry05** [comment]
Ahhh thx so much man great!

**Comment by Dry05** [comment]
it's still not working the same warning as i said earlier when compiling de dylib and when i start the app it crashes

**Comment by shuoshi** [comment]
Could u send me a crash log in system privacy? I'll have a check. Email:buaacss#gmail.com
